<definitions name="initRight" targetNamespace="http://localhost/LogoWeb/web/app.php/soap" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://localhost/LogoWeb/web/app.php/soap" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <portType name="initRightPortType">
        <operation name="initRight">
            <input message="tns:initRightRequest"/>
            <output message="tns:initRightResponse"/>
        </operation>
    </portType>
    <types>
        <xsd:schema targetNamespace="http://localhost/LogoWeb/web/app.php/soap/init"/>
    </types>
    <message name="initRightRequest">
        <part name="numTpe" type="xsd:string"/>
    </message>
    <message name="initRightResponse">
        <part name="right" type="xsd:string"/>
    </message>
    <service name="initRightService">
        <port name="initRightPort" binding="tns:initRightBinding">
            <soap:address location="http://localhost/LogoWeb/web/app.php/soap/init"/>
        </port>
    </service>
    <binding name="initRightBinding" type="tns:initRightPortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
        <operation name="initRight">
            <soap:operation soapAction="http://localhost/LogoWeb/web/app.php/soap/init"/>
            <input>
                <soap:body use="literal" namespace="http://localhost/LogoWeb/web/app.php/soap/init" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://localhost/LogoWeb/web/app.php/soap/init" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>
</definitions>