<definitions name="hello" targetNamespace="http://voisin.cib-ingenierie.fr/Soap/Hello" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://voisin.cib-ingenierie.fr/Soap/Hello" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <portType name="helloPortType">
        <operation name="hello">
            <input message="tns:helloRequest"/>
            <output message="tns:helloResponse"/>
        </operation>
    </portType>
    <types>
        <xsd:schema targetNamespace="http://voisin.cib-ingenierie.fr/Soap/Hello"/>
    </types>
    <message name="helloRequest">
        <part name="name" type="xsd:string"/>
    </message>
    <message name="helloResponse">
        <part name="return" type="xsd:string"/>
    </message>
    <service name="helloService">
        <port name="helloPort" binding="tns:helloBinding">
            <soap:address location="http://voisin.cib-ingenierie.fr/Soap/Hello"/>
        </port>
    </service>
    <binding name="helloBinding" type="tns:helloPortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
        <operation name="hello">
            <soap:operation soapAction="http://voisin.cib-ingenierie.fr/Soap/Hello"/>
            <input>
                <soap:body use="literal" namespace="http://voisin.cib-ingenierie.fr/Soap/Hello" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://voisin.cib-ingenierie.fr/Soap/Hello" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>
</definitions>