<?php

namespace Cib\Bundle\CustomerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * bankAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bankAccountRepository extends EntityRepository
{
}
