<?php

namespace Cib\Bundle\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * encloseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class encloseRepository extends EntityRepository
{
}
