<?php

namespace Cib\Bundle\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * resultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class resultsRepository extends EntityRepository
{

//    public function getAjaxResults($month,$dateStart,)
//    {
//
//    }
}
