<?php

namespace Cib\Bundle\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * clubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clubRepository extends EntityRepository
{
}
