<?php

namespace Cib\Bundle\ActivityBundle\Entity;

use Cib\Bundle\UserBundle\Entity\User;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * signboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class signboardRepository extends EntityRepository
{
    public function selectList(EntityManager $em,$search)
    {
        $dql = "SELECT s FROM CibActivityBundle:Signboard s WHERE (s.signboardName LIKE :search OR s.signboardNumber LIKE :search)";
        $query = $em->createQuery($dql);
        $query->setParameter('search','%'.$search.'%');

        return $signboards = $query->getResult();
    }

    public function getByUser(User $user, $search = null)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $queryBuilder->select('s')
            ->from('CibActivityBundle:Signboard', 's')
            ->where('s.user = ?1')
            ->andWhere('s.signboardName LIKE ?2')
            ->setParameter(1,$user)
            ->setParameter(2,'%'.$search.'%');
        $results = $queryBuilder->getQuery();
        return $results->getResult();
    }
}
