<?php

namespace Cib\Bundle\ActivityBundle\Entity;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * signboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class signboardRepository extends EntityRepository
{
    public function selectSignboardList(EntityManager $em,$search)
    {
        $dql = "SELECT s FROM CibActivityBundle:Signboard s WHERE (s.signboardName LIKE :search OR s.signboardNumber LIKE :search)";
        $query = $em->createQuery($dql);
        $query->setParameter('search','%'.$search.'%');

        return $signboards = $query->getResult();
    }
}
