<?php

namespace Cib\Bundle\ActivityBundle\Entity;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * storeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class storeRepository extends EntityRepository
{
    public function selectStoreList(EntityManager $em,$search)
    {
        $dql = "SELECT s FROM CibActivityBundle:Store s WHERE (s.storeName LIKE :search)";
        $query = $em->createQuery($dql);
        $query->setParameter('search','%'.$search.'%');

        return $signboards = $query->getResult();
    }

    public function selectAjaxStore(EntityManager $em,$search)
    {
        $dql = "SELECT s FROM CibActivityBundle:Store s WHERE (s.storeId = :search)";
        $query = $em->createQuery($dql);
        $query->setParameter('search',$search);

//        if($query->getResult())
//            return $query->getOneOrNullResult();
//        else
//            return new Store();
        return $query->getOneOrNullResult();
    }
}
