<?php

namespace Cib\Bundle\ActivityBundle\Entity;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * tpeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tpeRepository extends EntityRepository
{

    public function selectTpeList(EntityManager $em,$search)
    {
        $dql = "SELECT t FROM CibActivityBundle:Tpe t WHERE (t.tpeNumber LIKE :search)";
        $query = $em->createQuery($dql);
        $query->setParameter('search','%'.$search.'%');

        return $signboards = $query->getResult();
    }
}
